### ISSUE TITLE
Concern about starting fairness

### ISSUE THREAD

**Issue by DarwinPon** [DarwinPon/cs269_golf_sim#32]
I've just realized from the design sketch that the two starting locations may offer different opportunities and challenges, and there would be a concern about whether this is fair. I think we need to address this concern by making some updates to the rules. Potential changes include:

* setting a starting region (such as a box) on the board and players' balls are spawned inside it
* allowing the players to place there balls anywhere inside the starting region
* both players start from the exact same location, when the first player to move has launched his ball, the second player's ball spawns at the same starting position
* there are two different starting locations on the board, the second player gets to choose his starting location, and the first player has to start from the other one

To implement these rules, there would also need to be additional rules to determine which player moves first. Potentially we could:

* flip a coin to decide which player goes first
* let one player play first in two of three rounds, and the other player moves first in one of three rounds
* give the second player extra privileges, such as 
    - getting the first choice of starting location
    - getting to choose the order of the maps/levels

**Comment by chloezhang714** [comment]
I would prefer to make things simple here by starting both players from the exact same location, which also seems fair.

**Comment by BlitzenWang** [comment]
Based on my current thoughts on level design there'll be a starting area placed on one side of the level. And to address the problem of fairness, I'm considering giving players items at the start of every other turn. The second player can be the first one to get an item, which will compensate for the loss. Also every round we switch the player who gets to move first.
