### ISSUE TITLE
Starting Screen

### ISSUE THREAD

**Issue by ysu24** [DarwinPon/cs269_golf_sim#47]
We need a new background for our starting screen and some pictures of buttons. Buttons can be rectangles or any shape you like. And, the background and each button need to be separate images. 
Also, we need a bgm for the starting scene and a click sound when the player clicks the button.
Once you finish, you can put the new images in the pictures folder and the audio in a new folder called sound (you can create one if it is not there).

**Comment by chloezhang714** [comment]
I am thinking for the starting screen, we can use the picture of the golf ball as the button to start the game. I'll make the start screen and see how it works. A bgm and a click sound are still needed.

**Comment by sctyang2001** [comment]
I am currently working on the starting screen bgm, and the select (click) sound. Will have them by tomorrow. But, still do not know how to integrate them into the game.

**Comment by chloezhang714** [comment]
Thank you. Put them in a fold named audio and I should be able to take care of the rest!

**Comment by ryxGuo** [comment]
> I am thinking for the starting screen, we can use the picture of the golf ball as the button to start the game. I'll make the start screen and see how it works. A bgm and a click sound are still needed.

I actually made a start screen image which will be in the assets folder once it is merged. Let me know if you want me to change anything.

**Comment by chloezhang714** [comment]
@ryxGuo hey Ashley, could I get the RGB values of the yellow you used for the start screen image? Thanks!
